"""The house paragraph style, applied to any .docx (Ken, August 24 2026).

He asked for "a reasonable set of formatting attributes applied consistently across all
documents". THE NUMBERS ARE NOT INVENTED - each is the value already dominant across the
33 documents, so this makes the outliers agree with the majority rather than imposing a
new look:

    body prose     before 0, after 160   (474 paragraphs already; the generators' para())
    list items     before 0, after  80   (263 already, against 164 at 60 and 99 at 100)
    table cells    before 0, after   0   (the overwhelming majority already)

⚠ WHAT IT DELIBERATELY WILL NOT TOUCH, because a formatting pass that flattens something
somebody meant does real damage while looking tidy:

    HEADINGS            - 97% carry no direct spacing at all and take it from the style
                          definition, which is the right way round. Adding direct spacing
                          would make every document harder to restyle later.
    CENTERED paragraphs - figures and their captions. Centering is the discriminator:
                          body prose in these documents is never centered.
    Paragraphs with a
    DRAWING in them     - belt and braces for the same case.
    Anything already at
    240 TWIPS OR MORE   - title pages and deliberate breaks. 240 is 12pt; nothing in
                          ordinary prose reaches it by accident.
    THE CONTENTS LISTING - it is generated by Word from the headings.

Run:  python apply-doc-style.py [--check] <file.docx> [more...]
"""
import sys
from docx import Document
from lxml import etree

W = '{http://schemas.openxmlformats.org/wordprocessingml/2006/main}'
def q(t): return W + t

BODY = ('0', '160')
LIST = ('0', '80')
CELL = ('0', '0')
LEAVE_AT_OR_ABOVE = 240

def spacing(p):
    return p.find(q('pPr') + '/' + q('spacing'))

def current(p):
    sp = spacing(p)
    if sp is None:
        return (None, None)
    return (sp.get(W + 'before'), sp.get(W + 'after'))

def set_spacing(p, before, after):
    pPr = p.find(q('pPr'))
    if pPr is None:
        pPr = etree.Element(q('pPr'))
        p.insert(0, pPr)
    sp = pPr.find(q('spacing'))
    if sp is None:
        sp = etree.SubElement(pPr, q('spacing'))
    if sp.get(W + 'before') == before and sp.get(W + 'after') == after:
        return False
    sp.set(W + 'before', before)
    sp.set(W + 'after', after)
    return True

def classify(p):
    anc = [a.tag for a in p.iterancestors()]
    if q('sdt') in anc:
        return None                                   # the contents listing
    st = p.find(q('pPr') + '/' + q('pStyle'))
    name = str(st.get(W + 'val') or '') if st is not None else ''
    if name.lower().startswith('heading') or name.lower() == 'title':
        return None                                   # spacing belongs to the style
    jc = p.find(q('pPr') + '/' + q('jc'))
    if jc is not None and jc.get(W + 'val') in ('center', 'right'):
        return None                                   # figures, captions
    if p.find('.//' + q('drawing')) is not None:
        return None
    b, a = current(p)
    if any(v and v.isdigit() and int(v) >= LEAVE_AT_OR_ABOVE for v in (b, a)):
        return None                                   # title page, deliberate break
    if q('tc') in anc:
        return CELL
    if p.find(q('pPr') + '/' + q('numPr')) is not None:
        return LIST
    if not ''.join(x.text or '' for x in p.iter(q('t'))).strip():
        return None                                   # empty spacer paragraph
    return BODY

def apply(path, check_only=False):
    doc = Document(path)
    counts = {'body': 0, 'list': 0, 'cell': 0, 'left': 0}
    for p in doc.element.iter(q('p')):
        want = classify(p)
        if want is None:
            counts['left'] += 1
            continue
        key = 'body' if want is BODY else 'list' if want is LIST else 'cell'
        if current(p) != want:
            counts[key] += 1
            if not check_only:
                set_spacing(p, *want)
    if not check_only and (counts['body'] or counts['list'] or counts['cell']):
        doc.save(path)
    return ('body %(body)d, list %(list)d, cells %(cell)d changed; %(left)d left alone'
            % counts)

if __name__ == '__main__':
    check = '--check' in sys.argv
    for path in [a for a in sys.argv[1:] if a != '--check']:
        try:
            print('%-58s %s' % (path.split('/')[-1][:58], apply(path, check)))
        except Exception as e:
            print('%-58s SKIPPED: %s' % (path.split('/')[-1][:58], e))
