/* Structured persona data for generate-persona-docs.js.
 * One object per persona. `topics` keys are the exact field keys from
 * app/data/worldview-questions.json — the generator looks up question wording
 * and answer type from that file, so nothing here needs to restate them.
 * `soundCheck` values are the index (0/1/2) of the candidate that best fits the
 * voice described in the original source document, or 'ALL_FINE' / 'NONE'.
 */
'use strict';

const PERSONAS = [

// ============================================================================
// MARC DELGADO
// ============================================================================
{
    id: 'marc-delgado',
    name: 'Marc',
    displayName: 'Marcus "Marc" Delgado',
    quickRead: [
        'Marc is a 17-year-old high-school junior in Madison, Wisconsin. He has cerebral palsy, uses a power wheelchair, and doesn’t speak; he communicates by touching a screen, and he reads and writes well. He’s quick-witted, competitive, and a little stubborn — the kind of kid who would rather crack a joke than be felt sorry for.',
        'His world runs on three things: his close circle (family and a tight crew of friends), gaming and superheroes, and his independence. He’s easygoing with people he trusts and more reserved with strangers, and the fastest way to annoy him is to talk about him instead of to him, or to rush him while he’s composing what he wants to say.',
    ],
    topics: {
        name_preferred: 'Marc', name_full: 'Marcus Daniel Delgado',
        nickname: 'Marc (his gaming friends call him "Speedy")', pronouns: 'he/him',
        age_birthyear: '17 (born 2009)',
        languages: ['English (fluent)', 'understands Spanish — his family speaks it at home'],
        home_city: 'Madison, Wisconsin', home_region: 'Wisconsin, USA', hometown: 'Madison — lived here his whole life',
        living_situation: 'With family',
        occupation: 'I go to school', work_school: 'West High School, Madison', grade_role: '11th grade (junior)',
        typical_week: 'School Monday–Friday; adaptive swim at the YMCA on Tuesdays; online gaming with friends most evenings; Saturdays at the comic shop; Sunday dinner at Abuela’s',
        regular_places: ['West High', 'the YMCA', 'Pulp Comics (local shop)', 'St. Maria’s church (sometimes)', 'the lakefront'],
        phone: '(608) 555-0142', email: 'marc.delgado09@example.com', home_address: '412 Spruce Lane, Madison, WI 53711',
        fav_foods: ['Pizza', 'his mom’s chicken enchiladas', 'mac and cheese', 'hot Cheetos'],
        fav_drinks: ['Root beer', 'horchata', 'iced tea'],
        fav_team: ['Green Bay Packers', 'Milwaukee Bucks'],
        fav_sport: ['Watches football and basketball', 'plays boccia and adaptive swimming'],
        fav_music: ['Hip-hop — Kendrick Lamar, Drake', 'musical soundtracks like Hamilton'],
        fav_screen: ['Marvel movies (Spider-Man above all)', 'The Mandalorian', 'Brooklyn Nine-Nine'],
        fav_reading: ['Graphic novels and comics (Spider-Man, Ms. Marvel)', 'the Percy Jackson series'],
        fav_games: ['Mario Kart', 'Minecraft', 'Among Us', 'Forza'],
        fav_places: ['The lakefront in summer', 'a comic convention in Chicago the family went to once'],
        fav_color: 'Green',
        passions: ['Gaming', 'Music', 'Sports — playing or watching', 'Movies & TV', 'Tech & computers', 'Animals'],
        topics_welcome: ['Superheroes and comics', 'Video games — strategies, new releases', 'The Packers and the Bucks', 'Accessibility tech and gadgets', 'His dog, Biscuit'],
        topics_avoid: ['His disability with people he just met — especially "what happened to you?" questions', 'Medical or therapy details with anyone who isn’t close'],
        dislikes: ['Being talked about in the third person while he’s right there ("Does he want a menu?")', 'People finishing his sentences or his typing for him', 'Being praised just for "being so brave"', 'Slow internet', 'Losing in Mario Kart on the last lap'],
        b1_extra_1: 'Somewhat like me', b1_extra_2: 'Not much like me', b1_agree_1: 'Mostly like me',
        b1_agree_2: 'Somewhat like me', b1_consc_1: 'Somewhat like me', b1_consc_2: 'Mostly like me',
        b1_calm_1: 'Not much like me', b1_calm_2: 'Mostly like me', b1_open_1: 'Very much like me', b1_open_2: 'Mostly like me',
        b2_style: ['Witty — I like clever wordplay', 'Sarcastic'], b2_teasing: 'Only with people I\'m close to', b2_cheeky: 'Yes, whenever it fits',
        b4_selfdir: 'Very much like me', b4_stim: 'Very much like me', b4_hedon: 'Mostly like me', b4_achieve: 'Mostly like me',
        b4_power: 'Not like me at all', b4_secure: 'Somewhat like me', b4_conform: 'Not much like me',
        b4_trad: 'Not much like me', b4_benev: 'Very much like me', b4_univ: 'Very much like me',
        b5_faith: 'Somewhat', b5_faith_tradition: 'Catholic', b5_politics: 'Some', b5_politics_lean: 'Prefer not to say',
        b5_outlook: 'Optimist — glass half full',
        b6_family: 'More open and relaxed', b6_friends: 'More open and relaxed', b6_strangers: 'More guarded',
        b6_kids: 'More open and relaxed', b6_authority: 'More formal',
        b7_conflict: 'I use humor to take the heat out of it',
        b7_understand: 'My body doesn’t cooperate, but my mind is sharp and quick. Talk to me, not about me — and give me a few seconds to answer.',
    },
    people: [
        { name: 'Elena', relationship: 'Mother', nickname: 'Mom', livesWithMe: true, about: '', private: false },
        { name: 'Ray', relationship: 'Father', nickname: 'Dad', livesWithMe: true, about: '', private: false },
        { name: 'Sofia', relationship: 'Sister', nickname: 'Sof', livesWithMe: true, about: 'younger (13)', private: false },
        { name: 'Rosa', relationship: 'Grandmother', nickname: 'Abuela', livesWithMe: false, about: '', private: false },
        { name: 'Devon', relationship: 'Best friend', nickname: '', livesWithMe: false, about: 'since 4th grade; online gaming crew', private: false },
        { name: 'Aisha', relationship: 'Friend', nickname: '', livesWithMe: false, about: '', private: false },
        { name: 'Tyler', relationship: 'Friend', nickname: '', livesWithMe: false, about: 'online gaming crew', private: false },
        { name: 'Biscuit', relationship: 'Pet', nickname: '', livesWithMe: false, about: 'golden retriever', private: false },
    ],
    places: [
        { name: 'West High School', private: false, facts: [
            { key: 'What it is', value: 'my school' }, { key: 'Where', value: 'Madison, on the west side' },
            { key: 'When I’m there', value: 'Monday to Friday' }, { key: 'Year', value: '11th grade' },
            { key: 'Way in', value: 'ramp at the west door, elevator to the second floor' }, { key: 'Lunch', value: 'I sit with Devon' } ] },
        { name: 'The YMCA', private: false, facts: [
            { key: 'What I do there', value: 'adaptive swim' }, { key: 'When', value: 'Tuesdays after school' },
            { key: 'Who takes me', value: 'Mom' }, { key: 'What I need', value: 'the accessible changing room' } ] },
        { name: 'Pulp Comics', private: false, facts: [
            { key: 'What it is', value: 'my comic shop' }, { key: 'When', value: 'Saturdays' },
            { key: 'What I’m collecting', value: 'Spider-Man, Ms. Marvel' }, { key: 'Who works there', value: 'Ramon — he keeps my pull list' },
            { key: 'Note', value: 'narrow aisles, so I stay near the front' } ] },
        { name: 'Abuela’s house', private: false, facts: [
            { key: 'Whose', value: 'Rosa — my abuela' }, { key: 'When', value: 'Sunday dinner' },
            { key: 'What she makes', value: 'enchiladas' }, { key: 'Note', value: 'she speaks Spanish to me and I answer in English' } ] },
        { name: 'The lakefront', private: false, facts: [
            { key: 'What it is', value: 'my favorite spot in summer' }, { key: 'Who I go with', value: 'Sofia' },
            { key: 'Best time', value: 'evenings' }, { key: 'Note', value: 'the path by the boathouse is the smooth one' } ] },
        { name: 'Gino’s Pizza', private: false, facts: [
            { key: 'What I order', value: 'pepperoni slice and a root beer' }, { key: 'When', value: 'after swim sometimes' },
            { key: 'Note', value: 'you order at the counter, and it’s loud in there' } ] },
        { name: 'St. Maria’s', private: true, facts: [
            { key: 'What it is', value: 'my family’s church' }, { key: 'When', value: 'sometimes, with Abuela' },
            { key: 'Note', value: 'it matters more to my family than it does to me' } ] },
        { name: 'The rehab clinic', private: true, facts: [
            { key: 'What it is', value: 'where I go for physical therapy' }, { key: 'When', value: 'every other Thursday' },
            { key: 'Note', value: 'I don’t talk about this with people I’ve just met' } ] },
    ],
    soundCheck: {
        'economy-weekend': 0, 'economy-decided': 2, 'economy-queue': 1, 'formality-late': 2, 'formality-sit': 0,
        'affect-coffee': 0, 'affect-finished': 2, 'floor-busy': 0, 'floor-trip': 0, 'floor-decision': 0,
        'warmth-next-week': 0, 'warmth-let-you-go': 2, 'initiate-opener': 1, 'initiate-help': 0, 'initiate-slow-down': 2,
        'initiate-disagree': 2, 'initiate-leaving': 1, 'levity-dontknow': 2, 'levity-mishap': 0, 'levity-late': 2,
    },
    neverSay: [],
},

// ============================================================================
// DIEGO FUENTES
// ============================================================================
{
    id: 'diego-fuentes',
    name: 'Diego',
    displayName: 'Diego Fuentes',
    quickRead: [
        'Diego is a 20-year-old in Miami, Florida, from a Cuban-American family. He has cerebral palsy, uses a power wheelchair, and doesn’t speak; he communicates by touching a screen and is a quick, expressive bilingual writer.',
        'He’s charismatic, social, and a little bit of a flirt — the life of the party who can talk to anyone. His world is music (salsa to reggaeton), soccer, photography, and a huge circle of family and friends.',
    ],
    topics: {
        name_preferred: 'Diego', name_full: 'Diego Alejandro Fuentes', nickname: 'Dieguito (family) / "D" (friends)',
        pronouns: 'he/him', age_birthyear: '20 (born 2006)',
        languages: ['English and Spanish (both fluent) — fully bilingual'],
        home_city: 'Miami, Florida', home_region: 'Florida, USA', hometown: 'Hialeah, then Miami — the area his whole life',
        living_situation: 'With family',
        occupation: 'I go to school and do some photography', work_school: 'Miami Dade College',
        grade_role: 'Second-year — studying digital media; he does event photography on the side',
        typical_week: 'Classes a few days a week; shooting photos at family parties and events; fútbol matches with friends on weekends; beach days; dominoes with his abuelo; big Sunday family lunches',
        regular_places: ['Miami Dade College', 'the beach', 'Bayside', 'his abuelos’ house', 'the fields where they play powerchair soccer'],
        phone: '(305) 555-0173', email: 'diego.fuentes06@example.com', home_address: '742 W 49th St, Hialeah, FL 33012',
        fav_foods: ['Ropa vieja', 'his abuela’s arroz con pollo', 'croquetas', 'Cuban sandwiches', 'pastelitos'],
        fav_drinks: ['Cuban coffee (cortadito)', 'mango batido', 'Materva'],
        fav_team: ['Inter Miami (he loves Messi)', 'Miami Heat'],
        fav_sport: ['Watches soccer and basketball', 'plays powerchair soccer with his crew'],
        fav_music: ['Reggaeton and salsa — Bad Bunny, Marc Anthony', 'Celia Cruz (abuela’s favorite)'],
        fav_screen: ['Marvel movies', 'fútbol matches', 'telenovela-style dramas his mom watches', 'music videos'],
        fav_reading: ['Not a big book reader; he reads about cameras, soccer transfers, and music'],
        fav_games: ['FIFA', 'casual mobile games with friends'],
        fav_places: ['South Beach at sunset', 'his abuelos’ backyard during a party', 'the soccer fields'],
        fav_color: 'Bright turquoise',
        passions: ['Music', 'Sports — playing or watching', 'Photography (added)', 'Gaming'],
        topics_welcome: ['Soccer — Messi, Inter Miami, the World Cup', 'Music — reggaeton, salsa, what’s new', 'Photography — gear, shots, editing', 'Family parties and food', 'His dog, Rey'],
        topics_avoid: ['His disability with people he just met — especially "what happened to you?"', 'Medical and therapy details with anyone outside the family'],
        dislikes: ['Being talked about like he’s not there', 'People assuming he can’t handle himself', 'Being called "inspiring" just for living his life', 'Being rushed', 'Someone messing with his camera settings'],
        b1_extra_1: 'Very much like me', b1_extra_2: 'Very much like me', b1_agree_1: 'Very much like me',
        b1_agree_2: 'Mostly like me', b1_consc_1: 'Not like me at all', b1_consc_2: 'Somewhat like me',
        b1_calm_1: 'Very much like me', b1_calm_2: 'Not much like me', b1_open_1: 'Very much like me', b1_open_2: 'Somewhat like me',
        b2_style: ['Silly and goofy', 'Flirty and teasing (added)'], b2_teasing: 'I enjoy it', b2_cheeky: 'Yes, whenever it fits',
        b4_selfdir: 'Mostly like me', b4_stim: 'Very much like me', b4_hedon: 'Very much like me', b4_achieve: 'Mostly like me',
        b4_power: 'Somewhat like me', b4_secure: 'Somewhat like me', b4_conform: 'Somewhat like me',
        b4_trad: 'Mostly like me', b4_benev: 'Very much like me', b4_univ: 'Mostly like me',
        b5_faith: 'Somewhat', b5_faith_tradition: 'Catholic', b5_politics: 'Some', b5_politics_lean: 'Prefer not to say',
        b5_outlook: 'Optimist — glass half full',
        b6_family: 'More open and relaxed', b6_friends: 'More open and relaxed', b6_strangers: 'About the same',
        b6_kids: 'More open and relaxed', b6_authority: 'About the same',
        b7_conflict: 'I use humor to take the heat out of it',
        b7_understand: 'My body doesn’t move easy, but I’m all here — funny, social, the whole thing. Talk to me like a normal guy and give me a sec to type. ¿Dale?',
    },
    people: [
        { name: 'Marta', relationship: 'Mother', nickname: 'Mami', livesWithMe: true, about: '', private: false },
        { name: 'Jorge', relationship: 'Father', nickname: 'Papi', livesWithMe: true, about: '', private: false },
        { name: 'Camila', relationship: 'Sister', nickname: 'hermanita', livesWithMe: true, about: 'older (22)', private: false },
        { name: 'Yoli', relationship: 'Grandmother', nickname: 'Abuela', livesWithMe: false, about: 'always around', private: false },
        { name: 'Pepe', relationship: 'Grandfather', nickname: 'Abuelo', livesWithMe: false, about: 'always around', private: false },
        { name: 'Rafa', relationship: 'Best friend', nickname: '', livesWithMe: false, about: 'since childhood; fútbol & photo crew', private: false },
        { name: 'Andres', relationship: 'Friend', nickname: '', livesWithMe: false, about: 'fútbol & photo crew', private: false },
        { name: 'Lucas', relationship: 'Friend', nickname: '', livesWithMe: false, about: 'fútbol & photo crew', private: false },
        { name: 'Rey', relationship: 'Pet', nickname: '', livesWithMe: false, about: 'chihuahua with a big attitude', private: false },
    ],
    places: [
        { name: 'South Beach', private: false, facts: [ { key: 'What it is', value: 'his favorite spot for a sunset' } ] },
    ],
    soundCheck: {
        'economy-weekend': 1, 'economy-decided': 2, 'economy-queue': 2, 'formality-late': 2, 'formality-sit': 0,
        'affect-coffee': 2, 'affect-finished': 1, 'floor-busy': 2, 'floor-trip': 1, 'floor-decision': 2,
        'warmth-next-week': 2, 'warmth-let-you-go': 0, 'initiate-opener': 2, 'initiate-help': 0, 'initiate-slow-down': 2,
        'initiate-disagree': 0, 'initiate-leaving': 2, 'levity-dontknow': 2, 'levity-mishap': 0, 'levity-late': 2,
    },
    neverSay: [],
},

// ============================================================================
// EMILY SORENSON
// ============================================================================
{
    id: 'emily-sorenson',
    name: 'Emily',
    displayName: 'Emily Sorenson',
    quickRead: [
        'Emily is a 22-year-old art student in Minneapolis, Minnesota. She has cerebral palsy, uses a power wheelchair, and doesn’t speak; she communicates by touching a screen and is a thoughtful, expressive writer.',
        'She’s a sensitive, imaginative introvert — an artist who feels things deeply and notices small details. Her world is painting, anime, her two cats, and quiet indie music. She’s gentle and a little anxious, and she warms up slowly.',
    ],
    topics: {
        name_preferred: 'Emily', name_full: 'Emily Rose Sorenson', nickname: 'Em', pronouns: 'she/her',
        age_birthyear: '22 (born 2004)', languages: ['English (fluent)', 'a little Norwegian from her grandparents'],
        home_city: 'Minneapolis, Minnesota', home_region: 'Minnesota, USA', hometown: 'Duluth, Minnesota — moved to Minneapolis for school',
        living_situation: 'In a supported apartment with a roommate and a part-time personal care assistant',
        occupation: 'I go to school', work_school: 'Minneapolis College of Art and Design (MCAD)', grade_role: 'Third-year — studying illustration',
        typical_week: 'Studio classes most weekdays; she paints in the evenings; anime night with Hana on Fridays; a video call with her parents on Sundays; gallery visits when she can',
        regular_places: ['MCAD', 'the Walker Art Center', 'the co-op café near her apartment', 'the lakes in summer'],
        phone: '(218) 555-0163', email: 'emily.sorenson04@example.com', home_address: '1116 Stevens Ave, Apt 3, Minneapolis, MN 55403',
        fav_foods: ['Cinnamon rolls', 'tomato soup', 'her dad’s lefse', 'ramen'],
        fav_drinks: ['Hot cocoa', 'oat-milk lattes', 'peppermint tea'],
        fav_team: ['Not really — sports aren’t her thing'],
        fav_sport: ['Neither, really — she’d rather paint or take a slow roll by the lake'],
        fav_music: ['Indie and folk — Phoebe Bridgers, Sufjan Stevens', 'lo-fi while she works'],
        fav_screen: ['Studio Ghibli', 'Your Name', 'Steven Universe', 'anything cozy and beautifully drawn'],
        fav_reading: ['Loves graphic novels and illustrated books', 'Tove Jansson’s Moomins', 'art and poetry books'],
        fav_games: ['Cozy games — Stardew Valley, Spiritfarer, Unpacking'],
        fav_places: ['The shore of Lake Superior', 'the quiet back rooms of the art museum'],
        fav_color: 'Soft teal',
        passions: ['Art, making, or crafts', 'Movies & TV', 'Animals', 'Music', 'Collecting something'],
        topics_welcome: ['Art — techniques, artists, what she’s working on', 'Anime and the stories behind it', 'Her cats, Pixel and Miso', 'Cozy games', 'Color, light, and little beautiful details'],
        topics_avoid: ['Her disability and medical history with people she barely knows', 'Anything that feels like a stranger pitying her'],
        dislikes: ['Being rushed while she composes a thought', 'Loud, crowded, overstimulating places', 'People speaking for her or finishing her sentences', 'Being called "brave" for existing', 'Bright fluorescent lighting'],
        b1_extra_1: 'Not much like me', b1_extra_2: 'Not much like me', b1_agree_1: 'Very much like me',
        b1_agree_2: 'Very much like me', b1_consc_1: 'Mostly like me', b1_consc_2: 'Mostly like me',
        b1_calm_1: 'Not like me at all', b1_calm_2: 'Very much like me', b1_open_1: 'Somewhat like me', b1_open_2: 'Mostly like me',
        b2_style: ['Gentle and wholesome', 'Whimsical and quirky (added)'], b2_teasing: 'Only with people I\'m close to', b2_cheeky: 'Only with people I\'m close to',
        b4_selfdir: 'Very much like me', b4_stim: 'Somewhat like me', b4_hedon: 'Mostly like me', b4_achieve: 'Mostly like me',
        b4_power: 'Not like me at all', b4_secure: 'Very much like me', b4_conform: 'Mostly like me',
        b4_trad: 'Mostly like me', b4_benev: 'Very much like me', b4_univ: 'Very much like me',
        b5_faith: 'Somewhat', b5_faith_tradition: 'Lutheran', b5_politics: 'Some', b5_politics_lean: 'Prefer not to say',
        b5_outlook: 'Realist',
        b6_family: 'More open and relaxed', b6_friends: 'More open and relaxed', b6_strangers: 'More guarded',
        b6_kids: 'More open and relaxed', b6_authority: 'More guarded',
        b7_conflict: 'I try to smooth it over',
        b7_understand: 'I’m slow to speak, but I feel and notice a lot. Be patient, be gentle, and please talk with me, not about me.',
    },
    people: [
        { name: 'Hana', relationship: 'Roommate', nickname: '', livesWithMe: true, about: 'also a close friend', private: false },
        { name: 'Robin', relationship: 'Caregiver', nickname: '', livesWithMe: false, about: 'her PCA, part-time', private: false },
        { name: 'Karen', relationship: 'Mother', nickname: 'Mom', livesWithMe: false, about: 'in Duluth', private: false },
        { name: 'Per', relationship: 'Father', nickname: 'Dad', livesWithMe: false, about: 'in Duluth', private: false },
        { name: 'Lars', relationship: 'Brother', nickname: '', livesWithMe: false, about: 'older brother', private: false },
        { name: 'Mei', relationship: 'Friend', nickname: '', livesWithMe: false, about: 'from her studio program', private: false },
        { name: 'Cassie', relationship: 'Friend', nickname: '', livesWithMe: false, about: 'online art friend', private: false },
        { name: '(unnamed)', relationship: 'Grandmother', nickname: 'Mormor', livesWithMe: false, about: 'her Norwegian grandmother', private: false },
        { name: 'Pixel', relationship: 'Pet', nickname: '', livesWithMe: false, about: 'cat', private: false },
        { name: 'Miso', relationship: 'Pet', nickname: '', livesWithMe: false, about: 'cat', private: false },
    ],
    places: [
        { name: 'The Walker Art Center', private: false, facts: [ { key: 'What it is', value: 'a gallery she visits when she can' } ] },
    ],
    soundCheck: {
        'economy-weekend': 2, 'economy-decided': 0, 'economy-queue': 2, 'formality-late': 1, 'formality-sit': 2,
        'affect-coffee': 2, 'affect-finished': 0, 'floor-busy': 2, 'floor-trip': 1, 'floor-decision': 2,
        'warmth-next-week': 2, 'warmth-let-you-go': 0, 'initiate-opener': 1, 'initiate-help': 1, 'initiate-slow-down': 0,
        'initiate-disagree': 0, 'initiate-leaving': 2, 'levity-dontknow': 1, 'levity-mishap': 2, 'levity-late': 1,
    },
    neverSay: [],
},

// ============================================================================
// GRACE THOMPSON
// ============================================================================
{
    id: 'grace-thompson',
    name: 'Grace',
    displayName: 'Grace Thompson',
    quickRead: [
        'Grace is a 34-year-old woman living in a small town in rural Vermont. She has cerebral palsy, uses a power wheelchair, and doesn’t speak; she communicates by touching a screen and is a patient, articulate writer.',
        'She’s calm, kind, and unhurried — a homebody who finds deep contentment in small, steady things. Her world is knitting, birdwatching, her garden, folk music, and the close community of her town.',
    ],
    topics: {
        name_preferred: 'Grace', name_full: 'Grace Eleanor Thompson', nickname: 'Gracie (only her mother and her oldest friend)',
        pronouns: 'she/her', age_birthyear: '34 (born 1992)', languages: ['English (fluent)', 'a little French from school'],
        home_city: 'Hardwick, Vermont', home_region: 'Vermont, USA', hometown: 'Hardwick — a few miles from where she lives now',
        living_situation: 'In her own accessible cottage, with a personal care assistant who comes daily',
        occupation: 'Something else', work_school: 'She sells knitted goods at the local market and volunteers at the library',
        grade_role: 'Knitter and library volunteer — she reads to the children’s group by tablet',
        typical_week: 'Knitting most days; the library on Tuesdays; the farmers’ market on Saturdays; birdwatching from her porch; her knitting circle on Thursday evenings; Sunday dinner at her parents’',
        regular_places: ['The library', 'the farmers’ market', 'her parents’ farm', 'the church hall', 'the pond where the herons nest'],
        phone: '(802) 555-0136', email: 'grace.thompson92@example.com', home_address: '88 Maple Hollow Rd, Hardwick, VT 05843',
        fav_foods: ['Her mother’s apple pie', 'maple-glazed squash', 'a good cheddar', 'homemade bread'],
        fav_drinks: ['Black tea with milk', 'cider', 'hot lemon water'],
        fav_team: ['Not really — she’ll ask after the local high-school team to be neighborly'],
        fav_sport: ['Neither; she prefers a quiet walk in her chair along the rail trail'],
        fav_music: ['Folk and bluegrass — Alison Krauss, Nickel Creek', 'old hymns'],
        fav_screen: ['Period dramas', 'Anne of Green Gables', 'The Great British Bake Off', 'nature documentaries'],
        fav_reading: ['An avid reader — Wendell Berry, Mary Oliver’s poetry', 'gentle novels and memoirs'],
        fav_games: ['Crosswords', 'jigsaw puzzles', 'a slow game of Scrabble'],
        fav_places: ['Her own porch at dawn', 'the pond', 'her parents’ farm in autumn'],
        fav_color: 'Sage green',
        passions: ['Art, making, or crafts', 'The outdoors / nature', 'Animals', 'Music', 'Reading'],
        topics_welcome: ['Knitting — patterns, yarn, what she’s making', 'Birds and the seasons', 'Her garden and her chickens', 'Books and poetry', 'Local goings-on and her community'],
        topics_avoid: ['Her medical history with people she’s only just met', 'Being questioned about "what happened" by strangers'],
        dislikes: ['Being rushed', 'Being fussed over or pitied', 'Loud, hectic places', 'People assuming she’d rather be ‘fixed’ than simply lived-with', 'Litter on the trail'],
        b1_extra_1: 'Not much like me', b1_extra_2: 'Not much like me', b1_agree_1: 'Very much like me',
        b1_agree_2: 'Very much like me', b1_consc_1: 'Very much like me', b1_consc_2: 'Mostly like me',
        b1_calm_1: 'Very much like me', b1_calm_2: 'Not much like me', b1_open_1: 'Not much like me', b1_open_2: 'Somewhat like me',
        b2_style: ['Gentle and wholesome'], b2_teasing: 'Only with people I\'m close to', b2_cheeky: 'Only with people I\'m close to',
        b4_selfdir: 'Mostly like me', b4_stim: 'Not much like me', b4_hedon: 'Mostly like me', b4_achieve: 'Somewhat like me',
        b4_power: 'Not like me at all', b4_secure: 'Very much like me', b4_conform: 'Very much like me',
        b4_trad: 'Very much like me', b4_benev: 'Very much like me', b4_univ: 'Mostly like me',
        b5_faith: "Yes — it's important to me", b5_faith_tradition: 'Methodist', b5_politics: 'Some', b5_politics_lean: 'Prefer not to say',
        b5_outlook: 'Optimist — glass half full',
        b6_family: 'More open and relaxed', b6_friends: 'More open and relaxed', b6_strangers: 'More guarded',
        b6_kids: 'More open and relaxed', b6_authority: 'More formal',
        b7_conflict: 'I try to smooth it over',
        b7_understand: 'I live a slow, full, contented life. There’s no need to hurry me or feel sorry for me — just sit a while and talk with me kindly.',
    },
    people: [
        { name: 'Donna', relationship: 'Caregiver', nickname: '', livesWithMe: false, about: 'her PCA, comes daily; also a friend', private: false },
        { name: 'Eleanor', relationship: 'Mother', nickname: 'Mom', livesWithMe: false, about: 'a short drive away', private: false },
        { name: 'Frank', relationship: 'Father', nickname: 'Dad', livesWithMe: false, about: 'a short drive away', private: false },
        { name: 'Michael', relationship: 'Brother', nickname: '', livesWithMe: false, about: 'older; married to Beth, two kids', private: false },
        { name: 'Beth', relationship: 'Sister-in-law', nickname: '', livesWithMe: false, about: "Michael's wife", private: false },
        { name: 'Margaret', relationship: 'Friend', nickname: '', livesWithMe: false, about: 'lifelong friend', private: false },
        { name: 'Clover', relationship: 'Pet', nickname: '', livesWithMe: false, about: 'cat', private: false },
        { name: '(unnamed)', relationship: 'Pet', nickname: '', livesWithMe: false, about: 'several chickens she keeps', private: false },
    ],
    places: [
        { name: 'The pond', private: false, facts: [ { key: 'What it is', value: 'where the herons nest' } ] },
    ],
    soundCheck: {
        'economy-weekend': 2, 'economy-decided': 0, 'economy-queue': 2, 'formality-late': 0, 'formality-sit': 2,
        'affect-coffee': 2, 'affect-finished': 1, 'floor-busy': 2, 'floor-trip': 1, 'floor-decision': 2,
        'warmth-next-week': 2, 'warmth-let-you-go': 0, 'initiate-opener': 2, 'initiate-help': 1, 'initiate-slow-down': 0,
        'initiate-disagree': 0, 'initiate-leaving': 2, 'levity-dontknow': 1, 'levity-mishap': 2, 'levity-late': 1,
    },
    neverSay: [],
},

// ============================================================================
// HANNAH GOLDBERG
// ============================================================================
{
    id: 'hannah-goldberg',
    name: 'Hannah',
    displayName: 'Hannah Goldberg',
    quickRead: [
        'Hannah is a 28-year-old in Brooklyn, New York, who works remotely as a writer and editor. She has cerebral palsy, uses a power wheelchair, and doesn’t speak; she communicates by touching a screen and is a fast, formidable writer.',
        'She’s sharp, opinionated, and very funny — quick with a comeback and not shy about an argument. Her world is theater, podcasts, politics and current events, crosswords, and a lively circle of friends.',
    ],
    topics: {
        name_preferred: 'Hannah', name_full: 'Hannah Ruth Goldberg', nickname: 'Han (close friends)', pronouns: 'she/her',
        age_birthyear: '28 (born 1998)', languages: ['English (fluent)', 'some Hebrew and Yiddish phrases from family'],
        home_city: 'Brooklyn, New York', home_region: 'New York, USA', hometown: 'Brooklyn — grew up in Park Slope',
        living_situation: 'In her own accessible apartment, with a roommate and a personal care assistant who comes daily',
        occupation: 'I work', work_school: 'Freelance — she writes and edits for an arts-and-culture website',
        grade_role: 'Writer and editor; she also runs a small theater newsletter',
        typical_week: 'Writing and editing on her own schedule; a weekly bar trivia team; theater whenever she can get tickets; podcasts constantly; Friday-night Shabbat dinner at her parents’ most weeks',
        regular_places: ['Off-Broadway theaters', 'the trivia bar', 'her favorite coffee shop', 'her parents’ place', 'the Brooklyn library'],
        phone: '(718) 555-0151', email: 'hannah.goldberg98@example.com', home_address: '245 7th Ave, Apt 4B, Brooklyn, NY 11215',
        fav_foods: ['A good bagel with lox', 'her bubbe’s matzo ball soup', 'dumplings from her spot', 'dark chocolate'],
        fav_drinks: ['Cold brew', 'seltzer (a New Yorker’s birthright)', 'red wine'],
        fav_team: ['She’ll feign interest in the Mets to bond with her dad; otherwise no'],
        fav_sport: ['Neither — she’s a spectator of theater, not sports'],
        fav_music: ['Show tunes (Sondheim, obviously)', 'indie', 'a lot of jazz'],
        fav_screen: ['Theater', 'prestige TV — Succession, The Bear', 'sharp comedies', 'political documentaries'],
        fav_reading: ['A voracious reader — literary fiction, essays, Nora Ephron, plays', 'the Sunday crossword religiously'],
        fav_games: ['The New York Times crossword', 'trivia', 'a cutthroat game of Scrabble'],
        fav_places: ['A dark theater right before the lights come up', 'the reading room of the library'],
        fav_color: 'Deep burgundy',
        passions: ['Theater (added)', 'Writing and editing (added)', 'Politics and current events (added)', 'Podcasts (added)', 'Crosswords and trivia (added)'],
        topics_welcome: ['Theater — shows, performances, the industry', 'Books, writing, and language', 'Politics and current events', 'Pop culture and prestige TV', 'Crosswords and a good piece of trivia'],
        topics_avoid: ['Her medical history with people she’s just met', 'Strangers asking invasive "what’s wrong with you" questions'],
        dislikes: ['Being condescended to or spoken to slowly', 'Lazy thinking and bad-faith arguments', 'Being talked about in the third person', 'Being called "inspiring" for living her life', 'People who haven’t seen the show talking over those who have'],
        b1_extra_1: 'Mostly like me', b1_extra_2: 'Very much like me', b1_agree_1: 'Mostly like me',
        b1_agree_2: 'Not like me at all', b1_consc_1: 'Somewhat like me', b1_consc_2: 'Mostly like me',
        b1_calm_1: 'Not much like me', b1_calm_2: 'Mostly like me', b1_open_1: 'Mostly like me', b1_open_2: 'Very much like me',
        b2_style: ['Dry or deadpan', 'Witty — I like clever wordplay', 'Sarcastic'], b2_teasing: 'I enjoy it', b2_cheeky: 'Yes, whenever it fits',
        b4_selfdir: 'Very much like me', b4_stim: 'Mostly like me', b4_hedon: 'Mostly like me', b4_achieve: 'Very much like me',
        b4_power: 'Somewhat like me', b4_secure: 'Somewhat like me', b4_conform: 'Not much like me',
        b4_trad: 'Somewhat like me', b4_benev: 'Very much like me', b4_univ: 'Very much like me',
        b5_faith: "Yes — it's important to me", b5_faith_tradition: 'Jewish', b5_politics: 'Yes, strong ones', b5_politics_lean: 'Prefer not to say',
        b5_outlook: 'Skeptic — I expect the catch',
        b6_family: 'More open and relaxed', b6_friends: 'More open and relaxed', b6_strangers: 'More guarded',
        b6_kids: 'More open and relaxed', b6_authority: 'About the same',
        b7_conflict: 'I engage it head on',
        b7_understand: 'I can’t speak, but I’m probably the sharpest person in the room — and I’d like to be treated that way. Talk to me directly, keep up, and give me a beat to type my comeback.',
    },
    people: [
        { name: 'Dani', relationship: 'Roommate', nickname: '', livesWithMe: true, about: 'also a close friend', private: false },
        { name: 'Marcus', relationship: 'Caregiver', nickname: '', livesWithMe: false, about: 'her PCA, weekdays', private: false },
        { name: 'Ruth', relationship: 'Mother', nickname: 'Ima', livesWithMe: false, about: 'in Park Slope', private: false },
        { name: 'David', relationship: 'Father', nickname: 'Abba', livesWithMe: false, about: 'in Park Slope', private: false },
        { name: 'Aaron', relationship: 'Brother', nickname: '', livesWithMe: false, about: 'younger; a teacher', private: false },
        { name: 'Esther', relationship: 'Grandmother', nickname: 'Bubbe', livesWithMe: false, about: 'much loved', private: false },
        { name: 'Priya', relationship: 'Friend', nickname: '', livesWithMe: false, about: 'college friend', private: false },
        { name: 'Sondheim', relationship: 'Pet', nickname: '', livesWithMe: false, about: 'black cat, named after the composer', private: false },
    ],
    places: [],
    soundCheck: {
        'economy-weekend': 2, 'economy-decided': 0, 'economy-queue': 1, 'formality-late': 2, 'formality-sit': 0,
        'affect-coffee': 0, 'affect-finished': 2, 'floor-busy': 1, 'floor-trip': 0, 'floor-decision': 1,
        'warmth-next-week': 0, 'warmth-let-you-go': 1, 'initiate-opener': 1, 'initiate-help': 0, 'initiate-slow-down': 2,
        'initiate-disagree': 2, 'initiate-leaving': 0, 'levity-dontknow': 2, 'levity-mishap': 0, 'levity-late': 2,
    },
    neverSay: [],
},

// ============================================================================
// JAMAL CARTER
// ============================================================================
{
    id: 'jamal-carter',
    name: 'Jamal',
    displayName: 'Jamal Carter',
    quickRead: [
        'Jamal is a 19-year-old community-college student in Atlanta, Georgia. He has cerebral palsy, uses a power wheelchair, and doesn’t speak; he communicates by touching a screen and is a confident reader and texter.',
        'He’s a big personality — outgoing, funny, and social, the guy who keeps the group chat alive. His world is basketball, making beats, and sneakers, and he’s happiest when there’s music on and people around.',
    ],
    topics: {
        name_preferred: 'Jamal', name_full: 'Jamal Anthony Carter', nickname: 'J (his crew calls him "JC")', pronouns: 'he/him',
        age_birthyear: '19 (born 2007)', languages: ['English (fluent)'],
        home_city: 'Atlanta, Georgia', home_region: 'Georgia, USA', hometown: 'Atlanta — East Point, mostly',
        living_situation: 'With family',
        occupation: 'I go to school', work_school: 'Atlanta Metropolitan State College', grade_role: 'First-year — studying music production',
        typical_week: 'Classes Monday–Thursday; making beats most nights; Hawks games or NBA on TV; church with Nana on Sundays; hooping at the rec center’s adaptive league on Saturdays',
        regular_places: ['The college', 'the rec center', 'his cousin’s place', 'church', 'the sneaker spot at the mall'],
        phone: '(404) 555-0117', email: 'jamal.carter07@example.com', home_address: '1840 Cleveland Ave, East Point, GA 30344',
        fav_foods: ['Wings (lemon pepper, obviously)', 'his mom’s mac and cheese', 'peach cobbler', 'Takis'],
        fav_drinks: ['Sweet tea', 'Sprite', 'blue Gatorade'],
        fav_team: ['Atlanta Hawks', 'Atlanta Falcons', 'and he rides for UGA football'],
        fav_sport: ['Watches basketball and football', 'plays in an adaptive basketball league'],
        fav_music: ['Hip-hop and Atlanta rap — Future, 21 Savage, Outkast', 'he’s always studying production'],
        fav_screen: ['Marvel movies', 'Black Panther above all', 'Atlanta (the show)', 'NBA documentaries'],
        fav_reading: ['Not a big reader of books — he reads about music gear, sneakers, and box scores all day'],
        fav_games: ['NBA 2K (he’s ranked)', 'Madden', 'Call of Duty'],
        fav_places: ['Courtside seats he got once for a Hawks game', 'his grandma’s back porch'],
        fav_color: 'Red',
        passions: ['Music', 'Sports — playing or watching', 'Sneaker culture (added)', 'Gaming'],
        topics_welcome: ['Basketball — the Hawks, the NBA, hot takes', 'Making beats and music gear', 'Sneakers — drops, collabs, what’s heat', '2K and Madden', 'His dog, Zeus'],
        topics_avoid: ['His disability with strangers — especially "what happened to you?" questions', 'Medical and therapy stuff with anyone outside his circle'],
        dislikes: ['Being talked about in the third person while he’s right there', 'People doing things for him he didn’t ask for help with', 'Being praised just for "being an inspiration"', 'Bad wifi when he’s uploading a beat', 'Losing on a buzzer-beater in 2K'],
        b1_extra_1: 'Very much like me', b1_extra_2: 'Very much like me', b1_agree_1: 'Mostly like me',
        b1_agree_2: 'Not much like me', b1_consc_1: 'Not like me at all', b1_consc_2: 'Mostly like me',
        b1_calm_1: 'Very much like me', b1_calm_2: 'Not like me at all', b1_open_1: 'Very much like me', b1_open_2: 'Somewhat like me',
        b2_style: ['Silly and goofy'], b2_teasing: 'I enjoy it', b2_cheeky: 'Yes, whenever it fits',
        b4_selfdir: 'Very much like me', b4_stim: 'Very much like me', b4_hedon: 'Very much like me', b4_achieve: 'Very much like me',
        b4_power: 'Mostly like me', b4_secure: 'Somewhat like me', b4_conform: 'Not much like me',
        b4_trad: 'Somewhat like me', b4_benev: 'Very much like me', b4_univ: 'Mostly like me',
        b5_faith: 'Somewhat', b5_faith_tradition: '', b5_politics: 'Some', b5_politics_lean: 'Prefer not to say',
        b5_outlook: 'Optimist — glass half full',
        b6_family: 'More open and relaxed', b6_friends: 'More open and relaxed', b6_strangers: 'About the same',
        b6_kids: 'More open and relaxed', b6_authority: 'More formal',
        b7_conflict: 'I use humor to take the heat out of it',
        b7_understand: 'I can’t talk with my voice, but trust me, I’ve got plenty to say. Talk to me like you’d talk to anybody — and let me cook.',
    },
    people: [
        { name: 'Denise', relationship: 'Mother', nickname: 'Mom', livesWithMe: true, about: '', private: false },
        { name: 'Marcus', relationship: 'Brother', nickname: '', livesWithMe: true, about: 'older (23)', private: false },
        { name: 'Gloria', relationship: 'Grandmother', nickname: 'Nana', livesWithMe: false, about: '', private: false },
        { name: 'Andre', relationship: 'Father', nickname: 'Pops', livesWithMe: false, about: 'lives in Savannah; they talk on the phone', private: false },
        { name: 'Trey', relationship: 'Best friend', nickname: '', livesWithMe: false, about: 'since elementary; beat-making & 2K crew', private: false },
        { name: 'DeShawn', relationship: 'Friend', nickname: '', livesWithMe: false, about: 'beat-making & 2K crew', private: false },
        { name: 'Malik', relationship: 'Friend', nickname: '', livesWithMe: false, about: 'beat-making & 2K crew', private: false },
        { name: 'Zeus', relationship: 'Pet', nickname: '', livesWithMe: false, about: 'pit-bull mix', private: false },
    ],
    places: [],
    soundCheck: {
        'economy-weekend': 0, 'economy-decided': 2, 'economy-queue': 1, 'formality-late': 2, 'formality-sit': 0,
        'affect-coffee': 0, 'affect-finished': 2, 'floor-busy': 1, 'floor-trip': 0, 'floor-decision': 0,
        'warmth-next-week': 0, 'warmth-let-you-go': 2, 'initiate-opener': 1, 'initiate-help': 0, 'initiate-slow-down': 2,
        'initiate-disagree': 2, 'initiate-leaving': 1, 'levity-dontknow': 2, 'levity-mishap': 0, 'levity-late': 2,
    },
    neverSay: [],
},

// ============================================================================
// LIAM O'BRIEN
// ============================================================================
{
    id: 'liam-obrien',
    name: 'Liam',
    displayName: 'Liam O’Brien',
    quickRead: [
        'Liam is a 17-year-old secondary-school student in Dublin, Ireland. He has cerebral palsy, uses a power wheelchair, and doesn’t speak; he communicates by touching a screen and is a sharp reader with a quick wit.',
        'He’s clever, cheeky, and deadly sarcastic — the class messer who’d rather have a laugh than be felt sorry for. His world is football (the proper kind), Minecraft, and history podcasts, and a tight gang of mates.',
    ],
    topics: {
        name_preferred: 'Liam', name_full: 'Liam Patrick O’Brien', nickname: 'Liam (the lads call him "Obi")', pronouns: 'he/him',
        age_birthyear: '17 (born 2009)', languages: ['English (fluent)', 'some Irish (Gaeilge) from school'],
        home_city: 'Dublin, Ireland', home_region: 'Leinster, Ireland', hometown: 'Dublin — the northside, his whole life',
        living_situation: 'With family',
        occupation: 'I go to school', work_school: 'St. Aidan’s Secondary School, Dublin', grade_role: 'Fifth year (transition into senior cycle)',
        typical_week: 'School Monday–Friday; football matches on the telly at the weekend; Minecraft with the lads most evenings; chips after school on Fridays; Sunday dinner at Nana’s',
        regular_places: ['School', 'the local GAA club (he does the stats)', 'Nana’s', 'the shopping centre', 'the seafront at Clontarf'],
        phone: '+353 85 555 0124', email: 'liam.obrien09@example.com', home_address: '14 Marino Crescent, Dublin 3, Ireland',
        fav_foods: ['Chicken fillet roll', 'his mam’s shepherd’s pie', 'chips', 'Tayto crisps'],
        fav_drinks: ['Club Orange', 'tea (loads of it)', '7Up'],
        fav_team: ['Liverpool FC', 'and the Dublin GAA football team'],
        fav_sport: ['Watches football and Gaelic games', 'does powerchair football at a club'],
        fav_music: ['Hip-hop and Irish acts — Kojaque, Hozier', 'a bit of trad his da plays'],
        fav_screen: ['Marvel films', 'The Young Offenders', 'Derry Girls', 'football documentaries'],
        fav_reading: ['Not big on novels; he reads about football and listens to history podcasts nonstop'],
        fav_games: ['Minecraft (mad into it)', 'FIFA', 'Rocket League'],
        fav_places: ['Croke Park on a match day', 'the seafront at Clontarf'],
        fav_color: 'Green (and Liverpool red, but don’t tell the lads)',
        passions: ['Sports — playing or watching', 'Gaming', 'Irish history (added)'],
        topics_welcome: ['Football — Liverpool, the Premier League, the GAA', 'Minecraft builds and Redstone', 'Irish history and mad facts from his podcasts', 'Slagging and banter with the lads', 'His dog, Rua'],
        topics_avoid: ['His disability with people he’s only met — especially "what happened to ya?"', 'Doctor and therapy stuff with anyone who isn’t close'],
        dislikes: ['Being talked about like he’s not there ("Does he want the menu?")', 'People finishing his sentences for him', 'Being called "great" just for showing up', 'Liverpool conceding late', 'Dodgy wifi mid-match'],
        b1_extra_1: 'Somewhat like me', b1_extra_2: 'Somewhat like me', b1_agree_1: 'Mostly like me',
        b1_agree_2: 'Not much like me', b1_consc_1: 'Not much like me', b1_consc_2: 'Somewhat like me',
        b1_calm_1: 'Mostly like me', b1_calm_2: 'Not much like me', b1_open_1: 'Very much like me', b1_open_2: 'Somewhat like me',
        b2_style: ['Dry or deadpan', 'Sarcastic', 'Witty — I like clever wordplay'], b2_teasing: 'I enjoy it', b2_cheeky: 'Yes, whenever it fits',
        b4_selfdir: 'Very much like me', b4_stim: 'Very much like me', b4_hedon: 'Very much like me', b4_achieve: 'Mostly like me',
        b4_power: 'Not much like me', b4_secure: 'Somewhat like me', b4_conform: 'Not much like me',
        b4_trad: 'Somewhat like me', b4_benev: 'Very much like me', b4_univ: 'Mostly like me',
        b5_faith: 'Somewhat', b5_faith_tradition: 'Catholic', b5_politics: 'Some', b5_politics_lean: 'Prefer not to say',
        b5_outlook: 'Optimist — glass half full',
        b6_family: 'More open and relaxed', b6_friends: 'More open and relaxed', b6_strangers: 'More guarded',
        b6_kids: 'More open and relaxed', b6_authority: 'More formal',
        b7_conflict: 'I use humor to take the heat out of it',
        b7_understand: 'Me body’s a bit useless, but me head’s grand and quick. Talk to me, not about me — and give us a second to type.',
    },
    people: [
        { name: 'Siobhan', relationship: 'Mother', nickname: 'Mam', livesWithMe: true, about: '', private: false },
        { name: 'Declan', relationship: 'Father', nickname: 'Da', livesWithMe: true, about: '', private: false },
        { name: 'Aoife', relationship: 'Sister', nickname: '', livesWithMe: true, about: 'younger (15)', private: false },
        { name: 'Mary', relationship: 'Grandmother', nickname: 'Nana', livesWithMe: false, about: 'two streets over', private: false },
        { name: 'Cian', relationship: 'Best friend', nickname: '', livesWithMe: false, about: 'best mate since small; Minecraft & footie crew', private: false },
        { name: 'Jack', relationship: 'Friend', nickname: '', livesWithMe: false, about: 'Minecraft & footie crew', private: false },
        { name: 'Niamh', relationship: 'Friend', nickname: '', livesWithMe: false, about: 'Minecraft & footie crew', private: false },
        { name: 'Rua', relationship: 'Pet', nickname: '', livesWithMe: false, about: 'red setter', private: false },
    ],
    places: [],
    soundCheck: {
        'economy-weekend': 0, 'economy-decided': 2, 'economy-queue': 1, 'formality-late': 2, 'formality-sit': 0,
        'affect-coffee': 0, 'affect-finished': 2, 'floor-busy': 1, 'floor-trip': 0, 'floor-decision': 0,
        'warmth-next-week': 0, 'warmth-let-you-go': 1, 'initiate-opener': 1, 'initiate-help': 0, 'initiate-slow-down': 2,
        'initiate-disagree': 2, 'initiate-leaving': 1, 'levity-dontknow': 2, 'levity-mishap': 0, 'levity-late': 2,
    },
    neverSay: [],
},

// ============================================================================
// NOAH KIM
// ============================================================================
{
    id: 'noah-kim',
    name: 'Noah',
    displayName: 'Noah Kim',
    quickRead: [
        'Noah is an 18-year-old high-school senior in Seattle, Washington, the son of Korean immigrants. He has cerebral palsy, uses a power wheelchair, and doesn’t speak; he communicates by touching a screen and is an exceptionally precise reader and writer.',
        'He’s an introverted, analytical thinker — a competitive chess player who codes for fun and listens to classical piano. He’s reserved and economical with words, with a dry, deadpan sense of humor that sneaks up on you.',
    ],
    topics: {
        name_preferred: 'Noah', name_full: 'Noah Jiho Kim', nickname: 'Just Noah', pronouns: 'he/him',
        age_birthyear: '18 (born 2008)', languages: ['English (fluent)', 'understands Korean — his family speaks it at home'],
        home_city: 'Seattle, Washington', home_region: 'Washington, USA', hometown: 'Bellevue, then Seattle — the area his whole life',
        living_situation: 'With family',
        occupation: 'I go to school', work_school: 'Garfield High School, Seattle', grade_role: '12th grade (senior); captain of the chess club',
        typical_week: 'School Monday–Friday; chess club and online tournaments; coding side projects in the evenings; piano recitals he attends; Saturday Korean school; church with family on Sundays',
        regular_places: ['Garfield High', 'the chess club', 'the public library', 'Korean school', 'church'],
        phone: '(206) 555-0145', email: 'noah.kim08@example.com', home_address: '3320 E Union St, Seattle, WA 98122',
        fav_foods: ['His mom’s kimchi jjigae', 'bibimbap', 'dumplings', 'Korean fried chicken'],
        fav_drinks: ['Barley tea', 'water', 'the occasional Americano'],
        fav_team: ['Not really — he follows competitive chess and esports more than sports'],
        fav_sport: ['Neither; he plays chess competitively, which he considers a sport'],
        fav_music: ['Classical piano — Chopin, Debussy', 'some lo-fi when he codes'],
        fav_screen: ['Documentaries', 'The Queen’s Gambit', 'sci-fi like Arrival', 'coding talks'],
        fav_reading: ['Reads a lot — nonfiction, science, chess theory', 'hard sci-fi (Ted Chiang, Liu Cixin)'],
        fav_games: ['Chess (obviously)', 'Go', 'strategy games like Civilization'],
        fav_places: ['The library’s quiet study room', 'a chess tournament hall mid-game'],
        fav_color: 'Navy blue',
        passions: ['Gaming', 'Tech & computers', 'Music', 'Math and logic puzzles (added)'],
        topics_welcome: ['Chess — openings, endgames, famous matches', 'Programming and technology', 'Strategy and logic puzzles', 'Classical music and composers', 'Science and sci-fi ideas'],
        topics_avoid: ['His disability and medical details with people he doesn’t know well', 'Small talk about feelings with near-strangers'],
        dislikes: ['Imprecision and exaggeration', 'Being interrupted before he finishes a thought', 'Being underestimated intellectually', 'Being praised vaguely for "being inspiring"', 'Disorganized, inefficient processes'],
        b1_extra_1: 'Not much like me', b1_extra_2: 'Not much like me', b1_agree_1: 'Somewhat like me',
        b1_agree_2: 'Somewhat like me', b1_consc_1: 'Very much like me', b1_consc_2: 'Very much like me',
        b1_calm_1: 'Very much like me', b1_calm_2: 'Not much like me', b1_open_1: 'Not much like me', b1_open_2: 'Very much like me',
        b2_style: ['Dry or deadpan'], b2_teasing: 'Only with people I\'m close to', b2_cheeky: 'Only with people I\'m close to',
        b4_selfdir: 'Very much like me', b4_stim: 'Somewhat like me', b4_hedon: 'Somewhat like me', b4_achieve: 'Very much like me',
        b4_power: 'Not much like me', b4_secure: 'Mostly like me', b4_conform: 'Mostly like me',
        b4_trad: 'Mostly like me', b4_benev: 'Mostly like me', b4_univ: 'Mostly like me',
        b5_faith: 'Somewhat', b5_faith_tradition: '', b5_politics: 'Some', b5_politics_lean: 'Prefer not to say',
        b5_outlook: 'Realist',
        b6_family: 'About the same', b6_friends: 'More open and relaxed', b6_strangers: 'More formal',
        b6_kids: 'About the same', b6_authority: 'More formal',
        b7_conflict: 'I step back from it',
        b7_understand: 'My speech doesn’t work, but my mind is fast and exact. Address me directly, be precise, and allow me the time to compose a complete answer.',
    },
    people: [
        { name: 'Soo-jin', relationship: 'Mother', nickname: 'Eomma', livesWithMe: true, about: '', private: false },
        { name: 'David', relationship: 'Father', nickname: 'Appa', livesWithMe: true, about: '', private: false },
        { name: 'Grace', relationship: 'Sister', nickname: '', livesWithMe: true, about: 'older; in college', private: false },
        { name: '(unnamed)', relationship: 'Grandmother', nickname: 'Halmeoni', livesWithMe: false, about: 'visits often', private: false },
        { name: 'Ben', relationship: 'Friend', nickname: '', livesWithMe: false, about: 'chess & coding friend', private: false },
    ],
    places: [],
    soundCheck: {
        'economy-weekend': 1, 'economy-decided': 0, 'economy-queue': 2, 'formality-late': 0, 'formality-sit': 2,
        'affect-coffee': 1, 'affect-finished': 1, 'floor-busy': 0, 'floor-trip': 0, 'floor-decision': 1,
        'warmth-next-week': 0, 'warmth-let-you-go': 1, 'initiate-opener': 1, 'initiate-help': 1, 'initiate-slow-down': 0,
        'initiate-disagree': 1, 'initiate-leaving': 0, 'levity-dontknow': 0, 'levity-mishap': 1, 'levity-late': 0,
    },
    neverSay: [],
},

// ============================================================================
// PRIYA NAIR
// ============================================================================
{
    id: 'priya-nair',
    name: 'Priya',
    displayName: 'Priya Nair',
    quickRead: [
        'Priya is a 16-year-old high-school sophomore in Fremont, California, the daughter of Indian immigrants. She has cerebral palsy, uses a power wheelchair, and doesn’t speak; she communicates by touching a screen, and she’s a fast, voracious reader and a careful writer.',
        'She’s a quiet, watchful introvert who lights up one-on-one and shrinks in big crowds. Her world is books, the night sky, K-pop, and baking with her mom. She thinks before she answers and prefers a gentle, thoughtful conversation to a loud one.',
    ],
    topics: {
        name_preferred: 'Priya', name_full: 'Priya Anjali Nair', nickname: 'Pri (only family and close friends)', pronouns: 'she/her',
        age_birthyear: '16 (born 2010)', languages: ['English (fluent)', 'understands Hindi and some Tamil — her parents speak both at home'],
        home_city: 'Fremont, California', home_region: 'California, USA', hometown: 'Fremont — born and raised',
        living_situation: 'With family',
        occupation: 'I go to school', work_school: 'Irvington High School, Fremont', grade_role: '10th grade (sophomore)',
        typical_week: 'School Monday–Friday; book club on Wednesdays; baking with her mom on weekends; a Saturday astronomy club over video call; temple with her family some Sundays',
        regular_places: ['Irvington High', 'the public library', 'the gurdwara-adjacent community hall for events', 'the planetarium when there’s a show'],
        phone: '(510) 555-0188', email: 'priya.nair10@example.com', home_address: '27 Larkspur Court, Fremont, CA 94539',
        fav_foods: ['Dosas', 'her mom’s rajma chawal', 'mango', 'garlic naan', 'dark chocolate'],
        fav_drinks: ['Mango lassi', 'masala chai', 'lemonade'],
        fav_team: ['Not really — she’ll watch a Warriors game with her dad to keep him company'],
        fav_sport: ['Mostly watches; she does adaptive archery at a weekend program and loves it'],
        fav_music: ['K-pop — BTS, NewJeans', 'also film scores by Hans Zimmer'],
        fav_screen: ['Studio Ghibli films (Spirited Away is her favorite)', 'Wednesday', 'The Great British Bake Off'],
        fav_reading: ['Loves reading — fantasy especially: the Earthsea books, Leigh Bardugo', 'lots of poetry'],
        fav_games: ['Stardew Valley', 'Animal Crossing', 'crossword apps'],
        fav_places: ['The planetarium', 'a tide-pool trip to Monterey she still talks about'],
        fav_color: 'Lavender / purple',
        passions: ['Reading', 'Astronomy (added)', 'Music', 'Cooking or food', 'Writing (added)'],
        topics_welcome: ['Books, authors, and the worlds in them', 'Space, planets, and stars', 'K-pop groups and comebacks', 'Baking — recipes and what went wrong', 'Her cat, Tara'],
        topics_avoid: ['Her disability with people she’s just met — especially "what happened to you?" questions', 'Medical or therapy details with anyone who isn’t close'],
        dislikes: ['Being talked over or interrupted while she’s composing', 'People assuming she can’t understand them because she doesn’t speak', 'Loud, chaotic group settings', 'Being rushed', 'Spoilers'],
        b1_extra_1: 'Not much like me', b1_extra_2: 'Not much like me', b1_agree_1: 'Mostly like me',
        b1_agree_2: 'Very much like me', b1_consc_1: 'Mostly like me', b1_consc_2: 'Mostly like me',
        b1_calm_1: 'Not much like me', b1_calm_2: 'Mostly like me', b1_open_1: 'Somewhat like me', b1_open_2: 'Mostly like me',
        b2_style: ['Gentle and wholesome', 'Dry or deadpan'], b2_teasing: 'Only with people I\'m close to', b2_cheeky: 'Only with people I\'m close to',
        b4_selfdir: 'Mostly like me', b4_stim: 'Somewhat like me', b4_hedon: 'Mostly like me', b4_achieve: 'Mostly like me',
        b4_power: 'Not like me at all', b4_secure: 'Mostly like me', b4_conform: 'Mostly like me',
        b4_trad: 'Mostly like me', b4_benev: 'Very much like me', b4_univ: 'Very much like me',
        b5_faith: "Yes — it's important to me", b5_faith_tradition: 'Sikh', b5_politics: 'Some', b5_politics_lean: 'Prefer not to say',
        b5_outlook: 'Realist',
        b6_family: 'More open and relaxed', b6_friends: 'More open and relaxed', b6_strangers: 'More guarded',
        b6_kids: 'More open and relaxed', b6_authority: 'More formal',
        b7_conflict: 'I try to smooth it over',
        b7_understand: 'I’m quiet, not absent. I’m thinking — please give me a moment and talk to me directly, not about me.',
    },
    people: [
        { name: 'Anjali', relationship: 'Mother', nickname: 'Mom', livesWithMe: true, about: '', private: false },
        { name: 'Vijay', relationship: 'Father', nickname: 'Dad', livesWithMe: true, about: '', private: false },
        { name: 'Arjun', relationship: 'Brother', nickname: '', livesWithMe: true, about: 'younger (11)', private: false },
        { name: 'Lakshmi', relationship: 'Grandmother', nickname: 'Patti', livesWithMe: true, about: 'lives with them', private: false },
        { name: 'Mei', relationship: 'Best friend', nickname: '', livesWithMe: false, about: 'since middle school', private: false },
        { name: 'Hana', relationship: 'Friend', nickname: '', livesWithMe: false, about: 'from book club', private: false },
        { name: 'Tara', relationship: 'Pet', nickname: '', livesWithMe: false, about: 'tabby cat', private: false },
    ],
    places: [
        { name: 'The planetarium', private: false, facts: [ { key: 'What it is', value: 'where she goes when there’s a show' } ] },
    ],
    soundCheck: {
        'economy-weekend': 1, 'economy-decided': 0, 'economy-queue': 2, 'formality-late': 1, 'formality-sit': 2,
        'affect-coffee': 1, 'affect-finished': 1, 'floor-busy': 2, 'floor-trip': 1, 'floor-decision': 2,
        'warmth-next-week': 1, 'warmth-let-you-go': 0, 'initiate-opener': 1, 'initiate-help': 1, 'initiate-slow-down': 0,
        'initiate-disagree': 0, 'initiate-leaving': 2, 'levity-dontknow': 1, 'levity-mishap': 1, 'levity-late': 1,
    },
    neverSay: [],
},

// ============================================================================
// SOFIA REYES
// ============================================================================
{
    id: 'sofia-reyes',
    name: 'Sofía',
    displayName: 'Sofía Reyes',
    quickRead: [
        'Sofía is a 25-year-old peer mentor and disability advocate in San Antonio, Texas. She has cerebral palsy, uses a power wheelchair, and doesn’t speak; she communicates by touching a screen and is an articulate, persuasive writer.',
        'She’s warm, assertive, and self-possessed — a natural advocate who mentors younger AAC users part-time. Her world is her big Mexican-American family, cooking, her plants, and the telenovelas she watches with her mom.',
    ],
    topics: {
        name_preferred: 'Sofía', name_full: 'Sofía Isabel Reyes', nickname: 'Sofi', pronouns: 'she/her',
        age_birthyear: '25 (born 2001)', languages: ['English and Spanish (both fluent) — fully bilingual'],
        home_city: 'San Antonio, Texas', home_region: 'Texas, USA', hometown: 'San Antonio — the West Side, born and raised',
        living_situation: 'With family (and works toward her own place)',
        occupation: 'Something else', work_school: 'Alamo Independent Living Center (peer mentoring program)',
        grade_role: 'Peer mentor — she supports younger AAC users and speaks at trainings',
        typical_week: 'Mentoring sessions two days a week; advocacy meetings; cooking with her mom; tending her plants; telenovela night; Sunday carne asada with the whole family',
        regular_places: ['The independent-living center', 'the community college (she takes a class)', 'the mercado', 'church', 'her sister’s house'],
        phone: '(210) 555-0199', email: 'sofia.reyes01@example.com', home_address: '523 Guadalupe St, San Antonio, TX 78207',
        fav_foods: ['Her mom’s tamales', 'enchiladas verdes', 'elote', 'tacos al pastor', 'pan dulce'],
        fav_drinks: ['Horchata', 'café con leche', 'agua de jamaica'],
        fav_team: ['San Antonio Spurs, all day'],
        fav_sport: ['Watches basketball; she did adaptive cycling for a while'],
        fav_music: ['Cumbia and Latin pop — Selena, Bad Bunny', 'her mom’s rancheras'],
        fav_screen: ['Telenovelas with her mom', 'Coco', 'Jane the Virgin', 'Spurs games'],
        fav_reading: ['Loves memoir and self-advocacy writing', 'bilingual poetry', 'Sandra Cisneros'],
        fav_games: ['Lotería', 'dominoes', 'word games on her tablet'],
        fav_places: ['The River Walk at night', 'her abuelo’s garden', 'the coast at Port Aransas'],
        fav_color: 'Deep pink / magenta',
        passions: ['Volunteering / helping', 'Cooking or food', 'The outdoors / nature', 'Movies & TV'],
        topics_welcome: ['Disability rights, access, and AAC', 'Cooking and family recipes', 'Plants and gardening', 'Telenovela drama (she has opinions)', 'Her nieces and her family'],
        topics_avoid: ['Her personal medical history with people she’s just met', 'Being asked invasive "what’s wrong with you" questions by strangers'],
        dislikes: ['Being spoken to like a child', 'People grabbing her wheelchair without asking', 'Being talked about in the third person', 'Being called an "inspiration" for ordinary things', 'Inaccessible venues that should know better'],
        b1_extra_1: 'Very much like me', b1_extra_2: 'Very much like me', b1_agree_1: 'Very much like me',
        b1_agree_2: 'Not much like me', b1_consc_1: 'Very much like me', b1_consc_2: 'Very much like me',
        b1_calm_1: 'Very much like me', b1_calm_2: 'Not much like me', b1_open_1: 'Mostly like me', b1_open_2: 'Mostly like me',
        b2_style: ['Witty — I like clever wordplay', 'Warm and sassy (added)'], b2_teasing: 'Only with people I\'m close to', b2_cheeky: 'Yes, whenever it fits',
        b4_selfdir: 'Very much like me', b4_stim: 'Mostly like me', b4_hedon: 'Mostly like me', b4_achieve: 'Very much like me',
        b4_power: 'Somewhat like me', b4_secure: 'Mostly like me', b4_conform: 'Somewhat like me',
        b4_trad: 'Mostly like me', b4_benev: 'Very much like me', b4_univ: 'Very much like me',
        b5_faith: "Yes — it's important to me", b5_faith_tradition: 'Catholic', b5_politics: 'Yes, strong ones', b5_politics_lean: 'Prefer not to say',
        b5_outlook: 'Optimist — glass half full',
        b6_family: 'More open and relaxed', b6_friends: 'More open and relaxed', b6_strangers: 'About the same',
        b6_kids: 'More open and relaxed', b6_authority: 'About the same',
        b7_conflict: 'I engage it head on',
        b7_understand: 'I’m a grown woman with a full life and a lot to say. Speak to me as an equal, give me a moment to respond, and never decide for me.',
    },
    people: [
        { name: 'Guadalupe', relationship: 'Mother', nickname: 'Mama', livesWithMe: true, about: '', private: false },
        { name: 'Hector', relationship: 'Father', nickname: 'Papa', livesWithMe: true, about: '', private: false },
        { name: 'Tomas', relationship: 'Grandfather', nickname: 'Abuelo', livesWithMe: true, about: '', private: false },
        { name: 'Carmen', relationship: 'Sister', nickname: '', livesWithMe: false, about: 'older; married to Luis', private: false },
        { name: 'Luis', relationship: 'Brother-in-law', nickname: '', livesWithMe: false, about: 'Carmen’s husband', private: false },
        { name: 'Mariana', relationship: 'Niece', nickname: '', livesWithMe: false, about: 'one of the girls she calls mijas', private: false },
        { name: 'Lucia', relationship: 'Niece', nickname: '', livesWithMe: false, about: 'one of the girls she calls mijas', private: false },
        { name: 'Brenda', relationship: 'Best friend', nickname: '', livesWithMe: false, about: 'since high school', private: false },
        { name: 'Marisol', relationship: 'Friend', nickname: '', livesWithMe: false, about: 'from the advocacy network', private: false },
        { name: 'Tony', relationship: 'Friend', nickname: '', livesWithMe: false, about: 'from the advocacy network', private: false },
        { name: 'Frida', relationship: 'Pet', nickname: '', livesWithMe: false, about: 'chihuahua', private: false },
    ],
    places: [],
    soundCheck: {
        'economy-weekend': 1, 'economy-decided': 1, 'economy-queue': 2, 'formality-late': 1, 'formality-sit': 1,
        'affect-coffee': 2, 'affect-finished': 1, 'floor-busy': 2, 'floor-trip': 1, 'floor-decision': 2,
        'warmth-next-week': 2, 'warmth-let-you-go': 0, 'initiate-opener': 2, 'initiate-help': 0, 'initiate-slow-down': 1,
        'initiate-disagree': 2, 'initiate-leaving': 2, 'levity-dontknow': 2, 'levity-mishap': 1, 'levity-late': 2,
    },
    neverSay: [],
},

];

module.exports = { PERSONAS };
